import { Box } from '@chakra-ui/layout';
import { CacheProvider } from '@chakra-ui/next-js';
('use client');

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body>
        {/* <CacheProvider> */}
        <div>{children}</div>
        {/* </CacheProvider> */}
      </body>
    </html>
  );
}
